services:
  mysql:
    image: mysql:8.4.0
    container_name: mysql-8.4.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db: